name: Blade Tokens Upload

on: 
  workflow_dispatch:
    inputs:
      tokens:
        description: 'Token Object'
        required: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  token-upload:
    name: Upload Tokens
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.0
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Upload Tokens
        working-directory: packages/blade
        run: node ./scripts/uploadTokens.js '${{ github.event.inputs.tokens }}'
        env: 
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

