name: Blade Token Upload

on: 
  workflow_dispatch:
    inputs:
      tokens:
        description: 'Token Object'
        required: true

jobs:
  token-upload:
    name: Upload Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
      - name: Use Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: Test the script
        working-directory: packages/blade
        run: |
          echo "${{ github.event.inputs.tokens }}"
          node ./scripts/tokenUpload.js