name: Blade Tokens Upload Repo Dispatch

on: 
  repository_dispatch:
    types: upload

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  token-upload:
    name: Upload Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Use Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Upload Tokens
        working-directory: packages/blade
        run: node ./scripts/uploadTokens.js '${{ github.event.client_payload }}'
        env: 
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

